defmodule MarqueeWeb.OrgURL do
  @moduledoc """
  Builds org-scoped URLs that round-trip through tenant resolution.

  When `:marquee, :org_resolution` is `:query_param` (dev, staging, and any
  environment without wildcard subdomains), `org_url/2` appends `?org=slug`
  to the base URL so that the `SetOrganization` plug can resolve the tenant
  on the way back in. When the resolution mode is `:hostname`, the helper
  uses the configured `:tenant_host_pattern` or the organization's custom
  domain for absolute URLs and removes the `org` query parameter. Relative
  paths stay relative. Without a pattern, existing hostname URLs pass through.

  Use this helper for every URL generated by the app that will be passed to
  an external service or embedded in an email — Stripe checkout/portal,
  Stripe Connect onboarding, magic links, OAuth callbacks, etc. Anything
  that may be opened in a fresh browser context where the org slug would
  otherwise be lost.
  """

  @type org :: %{:slug => String.t(), optional(any()) => any()}
  @type mode :: :query_param | :hostname

  @doc """
  Returns an organization URL for the configured resolution mode.

  The resolution mode is read from `Application.get_env(:marquee, :org_resolution)`
  and defaults to `:query_param`.

  See `org_url/3` for a doctest-friendly variant that takes the mode explicitly.
  """
  @spec org_url(String.t(), org()) :: String.t()
  def org_url(base_url, org), do: org_url(base_url, org, resolution_mode())

  @doc """
  Returns `base_url` with `?org=slug` appended when `mode` is `:query_param`,
  or canonicalizes the hostname when `mode` is `:hostname` and a tenant host
  pattern is configured. Without a pattern, hostname URLs are unchanged.

  Existing query parameters are preserved; an existing `org` parameter is
  overwritten with the supplied org's slug.

  ## Examples

      iex> MarqueeWeb.OrgURL.org_url("https://app.example.com/admin", %{slug: "demo"}, :query_param)
      "https://app.example.com/admin?org=demo"

      iex> MarqueeWeb.OrgURL.org_url("https://app.example.com/admin?ref=email", %{slug: "demo"}, :query_param)
      "https://app.example.com/admin?org=demo&ref=email"

      iex> MarqueeWeb.OrgURL.org_url("https://app.example.com/admin?org=stale", %{slug: "demo"}, :query_param)
      "https://app.example.com/admin?org=demo"

      iex> MarqueeWeb.OrgURL.org_url("https://demo.example.com/admin", %{slug: "demo"}, :hostname)
      "https://demo.example.com/admin"
  """
  @spec org_url(String.t(), org(), mode()) :: String.t()
  def org_url(base_url, org, mode) do
    if provisioning_enabled?(),
      do: provisioned_url(base_url, org),
      else: legacy_url(base_url, org, mode)
  end

  defp legacy_url(base_url, %{slug: slug}, :query_param)
       when is_binary(base_url) and is_binary(slug) do
    append_org_param(base_url, slug)
  end

  defp legacy_url(base_url, %{slug: slug} = org, :hostname)
       when is_binary(base_url) and is_binary(slug) do
    case Application.get_env(:marquee, :tenant_host_pattern) do
      nil -> base_url
      pattern -> canonical_url(base_url, org, pattern)
    end
  end

  defp provisioned_url(base_url, org) do
    case Marquee.TenantDomains.ready_domain(org) do
      nil ->
        append_org_param(platform_url(base_url), org.slug)

      domain ->
        canonical_url(
          base_url,
          %{slug: org.slug, custom_domain: domain.hostname},
          domain.host_pattern
        )
    end
  end

  defp platform_url(base_url) do
    uri = URI.parse(base_url)
    cfg = Application.get_env(:marquee, MarqueeWeb.Endpoint, [])[:url] || []

    if uri.host,
      do:
        URI.to_string(%{
          uri
          | host: cfg[:host],
            scheme: cfg[:scheme] || uri.scheme,
            port: cfg[:port] || uri.port
        }),
      else: base_url
  end

  @doc """
  Builds a tenant hostname using an explicit pattern or custom domain.

      iex> MarqueeWeb.OrgURL.tenant_host(%{slug: "studio"}, "{slug}-app.example.com")
      "studio-app.example.com"
  """
  def tenant_host(org, pattern) do
    host = Map.get(org, :custom_domain)
    host = if host in [nil, ""], do: String.replace(pattern, "{slug}", org.slug), else: host
    if valid_host?(host), do: host, else: raise(ArgumentError, "invalid tenant hostname")
  end

  @doc """
  Extracts a tenant slug only when the entire hostname matches the pattern.

      iex> MarqueeWeb.OrgURL.tenant_slug("studio-app.example.com", "{slug}-app.example.com")
      "studio"
      iex> MarqueeWeb.OrgURL.tenant_slug("studio.evil.com", "{slug}-app.example.com")
      nil
  """
  def tenant_slug(host, pattern) when is_binary(host) and is_binary(pattern) do
    regex =
      pattern
      |> Regex.escape()
      |> String.replace(Regex.escape("{slug}"), "([a-z0-9](?:[a-z0-9-]*[a-z0-9])?)")

    if valid_host?(host) do
      case Regex.run(Regex.compile!("\\A" <> regex <> "\\z"), host) do
        [_, slug] -> slug
        _ -> nil
      end
    end
  end

  @doc "Resolves a custom domain or configured tenant hostname through Accounts."
  def resolve_host(host) when is_binary(host) do
    if provisioning_enabled?(),
      do: Marquee.TenantDomains.resolve_hostname(host),
      else: resolve_static_host(host)
  end

  def resolve_host(_), do: {:error, :not_found}

  defp resolve_static_host(host) do
    with {:error, _} <- Marquee.Accounts.get_organization_by_custom_domain(host),
         pattern when is_binary(pattern) <- Application.get_env(:marquee, :tenant_host_pattern),
         slug when is_binary(slug) <- tenant_slug(host, pattern) do
      Marquee.Accounts.get_organization_by_slug(slug)
    else
      {:ok, org} -> {:ok, org}
      _ -> {:error, :not_found}
    end
  end

  @doc "Redirects legacy platform GET/HEAD links to a known tenant, using Accounts lookup."
  def redirect_legacy(conn, _opts \\ []) do
    config = Application.get_env(:marquee, MarqueeWeb.Endpoint, [])[:url] || []
    conn = Plug.Conn.fetch_query_params(conn)

    with true <- provisioning_enabled?() or resolution_mode() == :hostname,
         pattern when is_binary(pattern) <- Application.get_env(:marquee, :tenant_host_pattern),
         true <- conn.host == config[:host] and conn.method in ["GET", "HEAD"],
         slug when is_binary(slug) and slug != "" <- conn.query_params["org"],
         {:ok, org} <- Marquee.Accounts.get_organization_by_slug(slug),
         true <-
           not provisioning_enabled?() or not is_nil(Marquee.TenantDomains.ready_domain(org)) do
      url = %{
        URI.new!("#{config[:scheme] || "https"}://#{conn.host}")
        | port: config[:port],
          path: conn.request_path,
          query: conn.query_string
      }

      location =
        if provisioning_enabled?(),
          do: provisioned_url(URI.to_string(url), org),
          else: canonical_url(URI.to_string(url), org, pattern)

      conn
      |> Plug.Conn.put_resp_header("location", location)
      |> Plug.Conn.send_resp(302, "")
      |> Plug.Conn.halt()
    else
      _ -> conn
    end
  end

  defp canonical_url(base_url, org, pattern) do
    uri = URI.parse(base_url)
    query = (uri.query || "") |> URI.decode_query() |> Map.delete("org") |> URI.encode_query()
    host = if uri.host, do: tenant_host(org, pattern), else: nil

    %{uri | host: host, query: if(query == "", do: nil, else: query)}
    |> URI.to_string()
  end

  defp valid_host?(host) do
    byte_size(host) <= 253 and
      Enum.all?(String.split(host, "."), fn label ->
        byte_size(label) <= 63 and Regex.match?(~r/\A[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\z/, label)
      end)
  end

  defp append_org_param(base_url, slug) do
    uri = URI.parse(base_url)

    query =
      (uri.query || "")
      |> URI.decode_query()
      |> Map.put("org", slug)
      |> URI.encode_query()

    %{uri | query: query} |> URI.to_string()
  end

  defp resolution_mode do
    Application.get_env(:marquee, :org_resolution, :query_param)
  end

  defp provisioning_enabled?,
    do: Application.get_env(:marquee, :tenant_domain_provisioning, [])[:enabled] == true
end
