#!/bin/sh
mix format --force
if [ $? -ne 0 ]; then
  echo "mix format --force failed. Fix the formatting error and re-stage your changes."
  exit 1
fi

mix compile --warnings-as-errors
if [ $? -ne 0 ]; then
  echo "mix compile --warnings-as-errors failed. Fix the compilation issue or warning before committing."
  exit 1
fi
