app = "bobine"
primary_region = "iad"

[build]

[deploy]
  release_command = "/app/bin/bobine eval \"Bobine.Release.migrate()\""

[env]
  PHX_HOST = "bobine.fly.dev"
  ECTO_IPV6 = "true"
  ERL_AFLAGS = "-proto_dist inet6_tcp"
  DNS_CLUSTER_QUERY = "bobine.internal"
  RELEASE_DISTRIBUTION = "name"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
