import Config

# Configure your database
config :marquee, Marquee.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "marquee_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 40

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :marquee, MarqueeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  url: [host: "localhost", port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "W6bQ5juXA07IHNT2Apm7mIAxVt6vFnWxmMZgxii+oDs10nnkmjNfgPv/5Q4MO39l",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:marquee, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:marquee, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :marquee, MarqueeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/marquee_web/router\.ex$",
      ~r"lib/marquee_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :marquee, dev_routes: true

# Store uploaded files on the local filesystem instead of DigitalOcean
# Spaces. Files land under `priv/static/uploads/` (gitignored) and are
# served by Plug.Static at `/uploads/<key>`. URLs are relative so they
# work across tenant subdomains. URLs written to the database while this
# client is active are dev-only — do not copy a dev DB to staging/prod.
config :marquee, Marquee.Storage,
  client: Marquee.Storage.LocalClient,
  bucket: "dev-local",
  region: "local",
  host: "localhost",
  public_url_base: "/uploads",
  local_upload_dir: Path.expand("../priv/static/uploads", __DIR__)

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable OTel trace export in dev to keep console clean
config :opentelemetry,
  traces_exporter: :none

# Mux CORS origin — use wildcard for dev since subdomains vary
# (e.g. demo.localhost:4000, test-channel.localhost:4000)
config :marquee, cors_origin: "*"

# Use Mux basic quality in dev. This is the lowest supported quality tier and
# is the closest match to the desired 720p/dev behavior.
config :marquee, mux_video_quality: "basic"

# MarqueeBot stats file path for dev dashboard
config :marquee, :bot_stats_file, "../marquee_bot/stats.jsonl"

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
