import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :marquee, MarqueeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :marquee, MarqueeWeb.Endpoint,
  force_ssl: [
    host: nil,
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Structured JSON logging, shipped to the OTLP hub by Marquee.Otel.Export.
# Includes trace context for log-to-trace correlation.
config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Basic,
     metadata: [
       :request_id,
       :trace_id,
       :span_id,
       :org_id,
       :org_slug,
       :user_id,
       :viewer_id,
       :reason,
       :error,
       :worker,
       :event_type,
       :status,
       :duration_ms,
       :asset_id,
       :stripe_event_id,
       :stripe_id,
       :stripe_subscription_id,
       :connect_account_id,
       :plan_id,
       :plan,
       :organization_id,
       :route,
       :view,
       :request_path,
       :upload_kind,
       :target_id,
       :content_type,
       :http_status,
       :response_body,
       :bytes_uploaded,
       :filename,
       :size,
       :spaces_key,
       :raw_params,
       :rejecting_webhook,
       :body
     ]}

# Production uploads should request Mux plus quality.
config :marquee, mux_video_quality: "basic"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
