defmodule BobineWeb.OrgURL do
  @moduledoc """
  Builds org-scoped URLs that round-trip through tenant resolution.

  When `:bobine, :org_resolution` is `:query_param` (dev, staging, and any
  environment without wildcard subdomains), `org_url/2` appends `?org=slug`
  to the base URL so that the `SetOrganization` plug can resolve the tenant
  on the way back in. When the resolution mode is `:hostname`, the helper
  is a passthrough — the host already identifies the tenant.

  Use this helper for every URL generated by the app that will be passed to
  an external service or embedded in an email — Stripe checkout/portal,
  Stripe Connect onboarding, magic links, OAuth callbacks, etc. Anything
  that may be opened in a fresh browser context where the org slug would
  otherwise be lost.
  """

  @type org :: %{:slug => String.t(), optional(any()) => any()}
  @type mode :: :query_param | :hostname

  @doc """
  Returns `base_url` with `?org=slug` appended when query-param resolution
  is enabled, otherwise returns `base_url` unchanged.

  The resolution mode is read from `Application.get_env(:bobine, :org_resolution)`
  and defaults to `:query_param`.

  See `org_url/3` for a doctest-friendly variant that takes the mode explicitly.
  """
  @spec org_url(String.t(), org()) :: String.t()
  def org_url(base_url, org), do: org_url(base_url, org, resolution_mode())

  @doc """
  Returns `base_url` with `?org=slug` appended when `mode` is `:query_param`,
  or `base_url` unchanged when `mode` is `:hostname`.

  Existing query parameters are preserved; an existing `org` parameter is
  overwritten with the supplied org's slug.

  ## Examples

      iex> BobineWeb.OrgURL.org_url("https://app.example.com/admin", %{slug: "demo"}, :query_param)
      "https://app.example.com/admin?org=demo"

      iex> BobineWeb.OrgURL.org_url("https://app.example.com/admin?ref=email", %{slug: "demo"}, :query_param)
      "https://app.example.com/admin?org=demo&ref=email"

      iex> BobineWeb.OrgURL.org_url("https://app.example.com/admin?org=stale", %{slug: "demo"}, :query_param)
      "https://app.example.com/admin?org=demo"

      iex> BobineWeb.OrgURL.org_url("https://demo.example.com/admin", %{slug: "demo"}, :hostname)
      "https://demo.example.com/admin"
  """
  @spec org_url(String.t(), org(), mode()) :: String.t()
  def org_url(base_url, %{slug: slug}, :query_param)
      when is_binary(base_url) and is_binary(slug) do
    append_org_param(base_url, slug)
  end

  def org_url(base_url, %{slug: slug}, :hostname)
      when is_binary(base_url) and is_binary(slug) do
    base_url
  end

  defp append_org_param(base_url, slug) do
    uri = URI.parse(base_url)

    query =
      (uri.query || "")
      |> URI.decode_query()
      |> Map.put("org", slug)
      |> URI.encode_query()

    %{uri | query: query} |> URI.to_string()
  end

  defp resolution_mode do
    Application.get_env(:bobine, :org_resolution, :query_param)
  end
end
